baseURL = "http://localhost"
languageCode = "en-us"
title = "Hands-On.Cloud"
theme = "hands-on-cloud"
pygmentsCodeFences = true
summaryLength = 40
enableRobotsTXT = true
timeout = 60000

[author]
    name = 'Andrei Maksimov'
    profile = 'Passionate Cloud Solutions Architect with 10+ years of experience.'
    avatar = 'https://avatars2.githubusercontent.com/u/1902417?s=460&v=4'

[Params]
    logo = "hands-on-cloud-logo.png"
    header = "Hands-On.Cloud"
    localeOgp = "en-us"
    og_image = "/hands-on-cloud-logo.png"
    sitename = "Hands-On.Cloud"
    description = "This open source project provides hands-on materials on different aspects of working in the clouds like AWS and GCP."
    keywords = "aws,devops,docker,terraform,cloudformation,serverless"
    twitter = "andreivmaksimov"
    github = "andreivmaksimov"
    facebook = "andrei.maksimov.3"
    linkedin = "avmaksimov"
    instagram = "andrei_v_maksimov"
    googleanalytics = "UA-137355839-1"
    googlecustomsearch = "005409723859646106283:xrxw99mawa4"
    toc = true

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"
