# Default values for wordpress-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: wordpress:4.8-apache
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

deployment:
  name: wordpress-deployment

service:
  name: wordpress-service
  type: NodePort
  port: 80
  nodePort: 32000


